; Apio project configuration file.
; See https://fpgawars.github.io/apio/docs/project-file for details.

; Selecting the default env
; Usage:
;   apio upload
[apio]
default-env = flash

; These settings are common to all envs.
[common]
top-module = main

; Use this env to program the flash (slow, non volatile).
; Usage:
;   apio upload -e flash
[env:flash]
board = icesugar-pro

; Use this env to program the ram (fast, volatile)
; Usage:
;   apio upload -e ram
[env:ram]
board = icesugar-pro-ram

